import React, { useRef, useState } from "react";
import { motion } from "framer-motion";
import { Upload, Camera, FileText, AlertTriangle, ScanEye, Loader2 } from "lucide-react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { detectWaste } from "@/lib/api";
import jsPDF from "jspdf";

const LABEL_COLORS = {
  plastic: "bg-primary",
  cardboard: "bg-warning",
  paper: "bg-slate-300",
  metal: "bg-violet",
  glass: "bg-secondary",
  trash: "bg-danger",
};

const PRIORITY_VARIANT = { Critical: "danger", High: "warning", Medium: "secondary", Low: "accent" };

function generateReportPdf(result, imageDataUrl) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  // Header
  doc.setFillColor(16, 122, 87);
  doc.rect(0, 0, pageWidth, 90, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("EcoVision AI", margin, 45);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text("Waste Detection Report", margin, 66);
  doc.setFontSize(9);
  doc.text(new Date().toLocaleString(), pageWidth - margin, 66, { align: "right" });

  y = 120;
  doc.setTextColor(20, 20, 20);

  // Image thumbnail if available
  if (imageDataUrl) {
    try {
      doc.addImage(imageDataUrl, "JPEG", margin, y, 160, 160, undefined, "FAST");
    } catch (e) {
      // If addImage fails on format, skip silently rather than breaking the report
    }
  }

  const textX = imageDataUrl ? margin + 180 : margin;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Detection Summary", textX, y + 16);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.text(`Predicted category: ${result.top_label}`, textX, y + 40);
  doc.text(`Confidence: ${result.top_confidence}%`, textX, y + 58);
  doc.text(`Risk level: ${result.risk_level}`, textX, y + 76);
  doc.text(`Cleanup priority: ${result.cleanup_priority}`, textX, y + 94);
  doc.text(`Risk score: ${result.risk_score} / 10`, textX, y + 112);

  y += 190;

  // Divider
  doc.setDrawColor(220, 220, 220);
  doc.line(margin, y, pageWidth - margin, y);
  y += 30;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Full Classification Breakdown", margin, y);
  y += 24;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  result.predictions.forEach((p) => {
    doc.setTextColor(20, 20, 20);
    doc.text(`${p.label.charAt(0).toUpperCase()}${p.label.slice(1)}`, margin, y);
    doc.text(`${p.confidence}%`, pageWidth - margin, y, { align: "right" });

    // Confidence bar
    const barY = y + 6;
    const barWidth = pageWidth - margin * 2;
    doc.setFillColor(235, 235, 235);
    doc.rect(margin, barY, barWidth, 6, "F");
    doc.setFillColor(16, 122, 87);
    doc.rect(margin, barY, (barWidth * p.confidence) / 100, 6, "F");

    y += 30;
  });

  y += 10;
  doc.setDrawColor(220, 220, 220);
  doc.line(margin, y, pageWidth - margin, y);
  y += 26;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Model Details", margin, y);
  y += 20;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(90, 90, 90);
  doc.text(`Model: ${result.model}`, margin, y);
  y += 16;
  doc.text(`Inference time: ${result.inference_ms} ms`, margin, y);
  y += 16;
  doc.text(`Detection ID: ${result.id}`, margin, y);
  y += 16;
  doc.text(`Logged at: ${new Date(result.created_at).toLocaleString()}`, margin, y);

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(9);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "Generated by EcoVision AI — AI-Powered Municipal Waste Classification",
    pageWidth / 2,
    pageHeight - 30,
    { align: "center" }
  );

  doc.save(`ecovision-report-${result.id}.pdf`);
}

export function DetectionPage() {
  const [image, setImage] = useState(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [generatingReport, setGeneratingReport] = useState(false);
  const inputRef = useRef(null);

  async function handleFile(file) {
    if (!file) return;
    setImage(URL.createObjectURL(file));
    setResult(null);
    setError(null);
    setAnalyzing(true);
    try {
      const data = await detectWaste(file);
      setResult(data);
    } catch (err) {
      const backendMessage = err?.response?.data?.detail;
      setError(
        backendMessage ||
          "Couldn't reach the detection API. Confirm the backend is running and VITE_API_URL is set."
      );
    } finally {
      setAnalyzing(false);
    }
  }

  async function handleGenerateReport() {
    if (!result) return;
    setGeneratingReport(true);
    try {
      // Convert the preview image to a data URL so it can be embedded in the PDF
      let imageDataUrl = null;
      if (image) {
        try {
          const response = await fetch(image);
          const blob = await response.blob();
          imageDataUrl = await new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onloadend = () => resolve(reader.result);
            reader.onerror = reject;
            reader.readAsDataURL(blob);
          });
        } catch (imgErr) {
          // If the image can't be embedded for any reason, still generate
          // the report without it rather than blocking the download.
          imageDataUrl = null;
        }
      }
      generateReportPdf(result, imageDataUrl);
    } finally {
      setGeneratingReport(false);
    }
  }

  return (
    <div className="mx-auto max-w-7xl px-6 py-10">
      <div className="mb-8">
        <h1 className="text-2xl font-extrabold tracking-tight">AI detection</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Upload a photo to run real waste classification and risk scoring.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        <Card
          onClick={() => inputRef.current?.click()}
          onDragOver={(e) => e.preventDefault()}
          onDrop={(e) => {
            e.preventDefault();
            handleFile(e.dataTransfer.files[0]);
          }}
          className="flex min-h-[380px] cursor-pointer flex-col items-center justify-center border-2 border-dashed border-border p-8 text-center transition-colors hover:border-primary/40"
        >
          <input
            ref={inputRef}
            type="file"
            accept="image/*"
            hidden
            onChange={(e) => handleFile(e.target.files[0])}
          />
          {!image ? (
            <>
              <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-primary/10">
                <Upload size={26} className="text-primary" />
              </div>
              <p className="mb-1 font-semibold">Drag & drop an image, or click to browse</p>
              <p className="mb-5 text-sm text-muted-foreground">PNG, JPG up to 10MB</p>
              <Button variant="outline" size="sm" onClick={(e) => e.stopPropagation()}>
                <Camera size={15} /> Use camera
              </Button>
            </>
          ) : (
            <img src={image} alt="Uploaded preview" className="max-h-80 max-w-full rounded-xl object-cover" />
          )}
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Detection results</CardTitle>
          </CardHeader>
          <CardContent>
            {!image && (
              <div className="flex h-64 flex-col items-center justify-center gap-3 text-center">
                <ScanEye size={28} className="text-muted-foreground" />
                <p className="max-w-[220px] text-sm text-muted-foreground">
                  Upload an image to see detected waste type, confidence, and risk level.
                </p>
              </div>
            )}

            {image && analyzing && (
              <div className="flex h-64 flex-col items-center justify-center gap-3">
                <motion.div
                  animate={{ rotate: 360 }}
                  transition={{ repeat: Infinity, duration: 0.9, ease: "linear" }}
                  className="h-10 w-10 rounded-full border-[3px] border-border border-t-primary"
                />
                <p className="text-sm text-muted-foreground">Running computer vision model...</p>
              </div>
            )}

            {image && !analyzing && error && (
              <div className="flex h-64 flex-col items-center justify-center gap-3 text-center">
                <AlertTriangle size={26} className="text-warning" />
                <p className="max-w-[260px] text-sm text-muted-foreground">{error}</p>
              </div>
            )}

            {image && !analyzing && result && (
              <div>
                <div className="mb-5 flex gap-2">
                  <Badge variant="warning">Risk: {result.risk_level}</Badge>
                  <Badge variant="danger">Priority: {result.cleanup_priority}</Badge>
                </div>
                <div className="space-y-3.5">
                  {result.predictions.map((p) => (
                    <div key={p.label}>
                      <div className="mb-1.5 flex justify-between text-sm">
                        <span className="font-semibold capitalize">{p.label}</span>
                        <span className="text-muted-foreground">{p.confidence}%</span>
                      </div>
                      <div className="h-1.5 overflow-hidden rounded-full bg-muted">
                        <motion.div
                          initial={{ width: 0 }}
                          animate={{ width: `${p.confidence}%` }}
                          transition={{ duration: 0.8, ease: "easeOut" }}
                          className={`h-full rounded-full ${LABEL_COLORS[p.label?.toLowerCase()] || "bg-primary"}`}
                        />
                      </div>
                    </div>
                  ))}
                </div>
                <p className="mb-4 mt-3 text-xs text-muted-foreground">
                  {result.model} · inference {result.inference_ms}ms · saved to database
                </p>
                <Button
                  className="w-full"
                  onClick={handleGenerateReport}
                  disabled={generatingReport}
                >
                  {generatingReport ? (
                    <>
                      <Loader2 size={15} className="animate-spin" /> Generating report...
                    </>
                  ) : (
                    <>
                      <FileText size={15} /> Generate AI report
                    </>
                  )}
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}